[package]
name = "crawler"
version = "0.1.0"
authors = ["gv"]
edition = "2018"

[dependencies]
getopts = "0.2"
lazy_static = "1.4.0"
log = "0.4.14"
once_cell = "1.8.0"
env_logger = "0.9.0"
actix-web = "3"
scraper = "0.12.0"
http = "0.2.4"
isahc = "1.4.0"
serde = "1.0.127"
serde_json = "1.0.66"
